const dataSetVersion = 'npc-sorter-1';
const dataSet = {};

dataSet[dataSetVersion] = {
  options: [
    ["Abel Mikaelson", ""],
    ["Adrián Lafferty", ""],
    ["Aisha Banks", ""],
    ["Alina Puig", ""],
    ["Amanda Hendrix", ""],
    ["Ángelo de Santos", ""],
    ["Anika Devyn", ""],
    ["Asher Vu", ""],
    ["Athenea Anderson", ""],
    ["Aurora Ashford", ""],
    ["Aveline Delaunay", ""],
    ["Benson Hendrix", ""],
    ["Bridget Reagan", ""],
    ["Caious Volturi", ""],
    ["Caleb Moore", ""],
    ["Cameron Kaleihn", ""],
    ["Camila Suárez", ""],
    ["Carol Bensiali", ""],
    ["Cathy Dove", ""],
    ["Ciro Vega", ""],
    ["Cole Keane", ""],
    ["Daniel Lewis", ""],
    ["Daphne Rosewood", ""],
    ["Darcie Barker", ""],
    ["Denis Rowen", ""],
    ["Derek Hale", ""],
    ["Diana Willow", ""],
    ["Edward Page", ""],
    ["Ethan Braun", ""],
    ["Evangeline Carlton", ""],
    ["Evie Miller", ""],
    ["Félix Áster", ""],
    ["Gavin Parks", ""],
    ["Héctor Basilea", ""],
    ["Isaac Porter", ""],
    ["Ian Smith", ""],
    ["Jade R. Marie", ""],
    ["JJ", ""],
    ["Josephine Cowper", ""],
    ["Keira Adams", ""],
    ["Killian Amsel", ""],
    ["Kylie Phoenix", ""],
    ["Kyra Moon", ""],
    ["Levi Rênard", ""],
    ["Lexie Santos", ""],
    ["Lillith Summers", ""],
    ["Maliah Blake", ""],
    ["Marcos Acuña", ""],
    ["Marlene Bellerose", ""],
    ["Máximo Cooper", ""],
    ["Melania Vasilaki", ""],
    ["Míkel Elizalde", ""],
    ["Nerón Turner", ""],
    ["Névian Williams", ""],
    ["Nicole Müller", ""],
    ["Nyxia Parker", ""],
    ["Octavia Larsen", ""],
    ["Olive Vandermeer", ""],
    ["Quinn Adams", ""],
    ["Reginald Black", ""],
    ["Robin", ""],
    ["Rochelle Silverstar", ""],
    ["Roderick Ink", ""],
    ["Rodrigo Santos", ""],
    ["Roxanna Mordane", ""],
    ["Salvador Rhodes", ""],
    ["Samuel Nova", ""],
    ["Sebastian Hale", ""],
    ["Selene Vasilaki", ""],
    ["Silas Hale", ""],
    ["Spencer Hastings", ""],
    ["Thea Anderson", ""],
    ["Theo Cooper", ""],
    ["Thomas Parker", ""],
    ["Valter Vandermeer", ""],
    ["Vinny", ""],
    ["Walton Lennis", ""],
    ["William Rawson", ""],
    ["Yoshi", ""],
    ["Yuna Mikaelson", ""]
  ]
};
